### ISSUE TITLE
Cannot be executed locally

### ISSUE THREAD

**Issue by stephenllai** [nov/openid_connect_sample_rp#6]
When the RP site "https://connect-rp.herokuapp.com/" running on Heroku is used, the operation can be completed properly.  It is then believed that the OP site is working properly.

However, when the RP site is running locally (clone it from GitHub, and then set it up according to the given instructions), it returns the error message "Client Registration Failed".

When it is checked at the server console of the local RP site, the following cause of error is found.
```
{"error":"invalid_redirect_uri","error_description":"Value of one or more redirect_uris is invalid."}
```

As further information, the following is shown on the server console.
```
{"application_type":"web","client_name":"NOV RP","subject_type":"pairwise","redirect_uris":["http://[ip of the local machine]:3001/providers/4/open_id"]}
```

**Comment by nov** [comment]
this is just a sample.
you can register any clients here.
moreover, you can run OP on your local.
